name: UsersAPI CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Docker compose up 
        run: |
          docker compose up --build -d

      - name: Run alembic migration on docker 
        run: |
          docker compose exec web alembic upgrade head

      - name: Run integration tests
        run: |
          docker compose exec web python -m pytest tests/integration/tests_users_routes.py/ --cov=api --cov-fail-under=80 -v

      - name: Run unit tests
        run: | 
          docker compose exec web python -m pytest tests/unit/tests_service.py --cov=services --cov-fail-under=70 -v

      - name: Stop docker
        run: |
          docker compose down


      - name: Debug on failure
        if: failure()
        run: |
          ls -la tests/
          cat requirements.txt
